### ISSUE TITLE
Actualizar SVG Tints y UI Colors

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/recursostech#26]
Los items se encuentran en la sección: https://www.recursostech.dev/docs/frontend/icons
 
La tarea consisten en actualizar sus SVG. 

Checklist de ayuda:

[ ] - Conseguir el SVG
[ ] - Verificar que sea negro, si no, pasarlo.
[ ] - Agrego el SVG dentro de la carpeta frontend que está en public, con el nombre correspondiente, ej: tint.svg
[ ] - En el item correspondiente, actualizo src dentro de cover para que el item sepa donde buscar su SVG
[ ] - Actualiar updatedAt con la fecha del día
[ ] - Agregar tu nombre de usuario en contributors

 ```yml
- imgPlaceholder: Tints
    titleCard: ''
    links:
      - type: 'Web'
        url: https://www.tints.dev/
    cover:
      src: '/frontend/tint.svg'
      height: 80
      width: 190
    createdAt: '2024-01-14T00:00:00Z'
    updatedAt: '2024-01-14T00:00:00Z'
    videos: []
```

PD: El SVG debe ser negro para que se vea correctamente tanto en Dark como en Light Mode.

Gracias ♥️ cualquier consulta no dudes en hacerla en el canal de Discord: https://discord.gg/vPCHkvqUEG o en este mismo Issue
