### ISSUE TITLE
Actualizar la 2da tanda de 4 SVG  de la sección icons

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/recursostech#28]
Ambos items se encuentran en la sección: https://www.recursostech.dev/docs/frontend/colors_palette 
 
![image](https://github.com/nsdonato/recursostech/assets/7875216/10a610e0-6331-4930-82c8-e003a0ba88d0)

La tarea consisten en actualizar sus SVG. 

Checklist de ayuda:

[ ] - Conseguir el SVG
[ ] - Verificar que sea negro, si no, pasarlo.
[ ] - Agrego el SVG dentro de la carpeta frontend que está en public, con el nombre correspondiente, ej: tint.svg
[ ] - En el item correspondiente, actualizo src dentro de cover para que el item sepa donde buscar su SVG
[ ] - Actualiar updatedAt con la fecha del día
[ ] - Agregar tu nombre de usuario en contributors 

EJ: Phosphoricons

 ```yml
  - imgPlaceholder: Phosphoricons
    titleCard: ''
    links:
      - type: 'Web'
        url: https://phosphoricons.com/
    cover:
      src: '/frontend/phosphoricons.svg'
      height: 80
      width: 190
    createdAt: '2024-01-14T00:00:00Z'
    updatedAt: '2024-01-28T00:00:00Z'
    videos: []
```

PD: El SVG debe ser negro para que se vea correctamente tanto en Dark como en Light Mode.

Gracias ♥️ cualquier consulta no dudes en hacerla en el canal de Discord: https://discord.gg/vPCHkvqUEG o en este mismo Issue
