### ISSUE TITLE
[📋 TO-DO] - Actualizar SVG de Railway y Fly.io

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/recursostech#55]
Los items se encuentran en la sección: https://www.recursostech.dev/docs/backend/deploys
 
La tarea consisten en actualizar sus SVG. 

Checklist de ayuda:

[ ] - Conseguir el SVG
[ ] - Verificar que sea negro, si no, pasarlo.
[ ] - Agrego el SVG dentro de la carpeta backend que está en public, con el nombre correspondiente, ej: tint.svg
[ ] - En el item correspondiente, actualizo src dentro de cover para que el item sepa donde buscar su SVG
[ ] - Agregar tu nombre de usuario en contributors

 ```yml
- imgPlaceholder: Railway
    titleCard: ''
    links:
      - type: 'Web'
        url: https://docs.railway.app/
    cover:
      src: '/backend/railway.svg'
      height: 80
      width: 190
    videos: []
```

> [!IMPORTANT]
> El SVG debe ser negro para que se vea correctamente tanto en Dark como en Light Mode.

Gracias ♥️ cualquier consulta no dudes en hacerla en el canal de Discord: https://discord.gg/vPCHkvqUEG o en este mismo Issue
