### ISSUE TITLE
[NEW 🆕] - Agregar Selenium webdriver

### ISSUE THREAD

**Issue by Char153** [nsdonato/recursostech#7]
**Por favor escribí la información necesaria del recurso para poder sumarla:**

Links:https://www.selenium.dev/documentation/webdriver/

- Web, Redes sociales (de ser necesario)
- ⚠️ Si es una extensión, poner la web (o si no tiene web, el repositorio) y el link a la extensión en el marketplace

Svg del recurso (opcional pero ideal):

- subir el svg al issue

Video (opcional):

- 🚨 Por el momento solo videos en español. Link al video de la persona explicando sobre el recurso, ej si es una extensión, como se usa.

**De ser necesario, sumar contexto adicional**
Añade aquí cualquier otro contexto o capturas de pantalla sobre la solicitud de función.

**Comment by nsdonato** [comment]
Gracias por el pedido! sea para mi o para otra persona: habría que agregar en la sección de testing/tools:

```
  - imgPlaceholder: Selenium
    titleCard: 'Selenium'
    links:
      - type: 'Web'
        url: https://www.selenium.dev/
    cover:
      src: ''
      height: 80
      width: 70
    createdAt: '2024-01-27T00:00:00Z'
    updatedAt: '2024-01-27T00:00:00Z'
    videos: []
```

(*) Tener en cuenta de poner las fechas de manera correcta createdAt y updatedAt
